# Generated by Django 5.2.7 on 2025-11-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlatformApp', '0002_user_bio_user_created_at_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='../static/profile.jpg', upload_to='../static'),
        ),
    ]
