# Generated by Django 5.2.8 on 2025-12-13 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlatformApp', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('speed', models.FloatField(default=1.0)),
                ('color', models.CharField(default='normal', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='chips',
            field=models.IntegerField(default=1000),
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('resolved', models.BooleanField(default=False)),
                ('won', models.BooleanField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GamePlatformApp.horse')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horses', models.ManyToManyField(related_name='race_participants', to='GamePlatformApp.horse')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_winner', to='GamePlatformApp.horse')),
            ],
        ),
    ]
