# Generated by Django 5.2.8 on 2025-12-13 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlatformApp', '0006_horse_user_chips_bet_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouletteField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('color', models.CharField(default='green', max_length=10)),
                ('won', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RouletteBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('bet_type', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fields', models.ManyToManyField(related_name='user_fields', to='GamePlatformApp.roulettefield')),
            ],
        ),
        migrations.CreateModel(
            name='RouletteWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.ManyToManyField(related_name='wheel_fields', to='GamePlatformApp.roulettefield')),
            ],
        ),
    ]
